### ISSUE TITLE
Sprite images missing from material?

### ISSUE THREAD

**Issue by Shmuwol** [learn-co-students/fe-quiz-05-v-000#1]
Quiz has 2 questions on Sprite images, but I don't remember it being covered in the material, i asked another student and he said he Just googled it.

**Comment by michaelsimon** [comment]
I noticed this as well.

**Comment by ga-be** [comment]
7-month update: still no mention of sprites in the material preceding this quiz. Still two questions concerning sprites.

**Comment by gj** [comment]
Fixed on the -curriculum repo, but changes don't seem to have propagated over here @pletcher 

https://github.com/learn-co-curriculum/fe-quiz-05/pull/13

**Comment by pletcher** [comment]
Merged manually
